### ISSUE TITLE
Build inspired lab

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#100]
@leenabusalem when you verify the steps please paste them in here, so @RaviHarsha can try on his end.

**Comment by fedebassetti** [comment]
@arturwhite1 Ravi encountered an install issue when setting up Jekyll. Did you have any issues installing it?

**Comment by fedebassetti** [comment]
@cwalters126 are you able to build?

**Comment by cwalters126** [comment]
No!

**Comment by RaviHarsha** [comment]
I somehow got Jekyll installed. I just followed the same steps mentioned and which we have went through yesterday.I feel today is the lucky day.

**Comment by fedebassetti** [comment]
@RaviHarsha great news! can you do the other steps to build and serve the pages?

**Comment by fedebassetti** [comment]
@cwalters126 what's the error? I think we have seen them all with @RaviHarsha & @leenabusalem

**Comment by RaviHarsha** [comment]
> @RaviHarsha great news! can you do the other steps to build and serve the pages?

Sure! I will try and let you know
