### ISSUE TITLE
add team member second row

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#106]
add a second row in the current team page to add additional members.

**Comment by RaviHarsha** [comment]
@fedebassetti: I have enhanced the code to reflect 2nd line Team pictures as well. Adding the screenshot of the new change.
There are 2 further changes which has to be done:
1) Art has to add his profile picture in the Github.
2) The Role designations has to be updated for the new joiners.

![image](https://user-images.githubusercontent.com/59711012/86808682-b1b39e00-c040-11ea-8a4b-e7c197cbfb75.png)

**Comment by fedebassetti** [comment]
@RaviHarsha Looks great!

@arturwhite1 please change your GitHub profile picture

**Comment by RaviHarsha** [comment]
I have done a mistake professor, I have added wrong id of Megan White. I have corrected it (meganwhite99), however we need even her to add her photo in Github.
