### ISSUE TITLE
About information update using the Readme file

### ISSUE THREAD

**Issue by RaviHarsha** [inspiredlab/inspiredlab.github.io#109]
@fedebassetti @arturwhite1 @cwalters126 @leenabusalem : I could successfully able to replicate the about me info in the profile. Its simple and straight forward having all the options to make the information look elegant. I have attached the step by step process. I would work on to add the link to this "About me" using the mundana theme.
[About me.docx](https://github.com/inspiredlab/inspiredlab.github.io/files/4929835/About.me.docx)

**Comment by fedebassetti** [comment]
@RaviHarsha 🙏 

rememberer prefer markdown for docs. See if you can make a version in .md

**Comment by RaviHarsha** [comment]
I have created "walkthrough" Makdown file which mentions the same steps in the doc updated above.
[](https://github.com/RaviHarsha/RaviHarsha)
