### ISSUE TITLE
Textarea issue with Commonmark markdown 

### ISSUE THREAD

**Issue by RaviHarsha** [inspiredlab/inspiredlab.github.io#119]
@fedebassetti @cwalters126 @leenabusalem @arturwhite1 As we all know that we are having a problem by using textarea tag in the Commonmark markdown. So, I have done some adjusting and trying to find a work around solution. Please suggest if the following view looks good to go with.

![image](https://user-images.githubusercontent.com/59711012/88811899-bcafa900-d17c-11ea-9d37-e434f2c5d758.png)

**Comment by fedebassetti** [comment]
@RaviHarsha Thanks for testing.

We need to disable the github markdown and go back to kramdown until we figure out a fix
