### ISSUE TITLE
HTTPS violation

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#19]
If you enable HTTPS for your site, and your site's HTML still references images, CSS, or JavaScript over HTTP, then your site is serving mixed content, and you may have trouble loading assets. Serving mixed content also makes your site less secure.

To remove your site's mixed content, improve your site's security, and resolve problems related to loading mixed content, edit your site's HTML files and change http:// to https:// so that all of your assets are served over HTTPS.

For GitHub Pages sites that use Jekyll, your HTML files will most likely be stored in the _layouts folder. In general, CSS is found in the <head> section of your HTML file. JavaScript is usually in the <head> section or just before the closing </body> tag. Images are often in the <body> section.

**Comment by fedebassetti** [comment]
we need to look where the issue is. It is possible that it might be in more than one repository.
It could potentially be the river crossing game repo

**Comment by fedebassetti** [comment]
I did remove one `http` reference in the game. 
Do we still have the warning for everybody or is it just for me?

**Comment by Stevendh** [comment]
There aren’t any published advisories. 

I think you've done it!

**Comment by fedebassetti** [comment]
@cwalters126 do you see any warning on yours?

**Comment by fedebassetti** [comment]
@inspiredlab/interns can you check and confirm that is all cleared? 
You can respond with the emoji in the top bar of this message.
