### ISSUE TITLE
find favicons for values

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#20]
make sure you match the version in the code (omis gazette uses fontawesome)

**Comment by cwalters126** [comment]
Update: Inspired lab is written to use the icons at font-awesome

**Comment by cwalters126** [comment]
Below are some options for our values; let me know which ones you prefer for each value, or you add one you like here too :) 


Learn: 

![5.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/97aae793-8781-4e97-9c19-592dd8d28147)
![5.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/520ea716-5f2e-4e51-b3f3-1fdc2342737a)
![7.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/1f215cbb-02a2-4718-870c-2658039d95bf)

Enthuse: 
![1.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/0e814a6b-6139-475b-8f97-8c798504925a)



Attentive:
![3.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/98522330-0cff-4efb-a138-a29aa24cbc4f)![4.png](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/247ecc90-7904-4eb3-88dc-89c1c9b645ad)
![2.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/f866f0d3-427f-458b-a9a8-d56f7d6f54a6)

Fortitude:
![8.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/c631cded-ffd8-4333-af6e-7e40452ee462)
![9.PNG](https://images.zenhubusercontent.com/5d36322d32dbcc71ddf34ea6/3385e3bb-63ea-48a4-a258-883a307e75ac)

**Comment by fedebassetti** [comment]
@cwalters126 which site did you use?

**Comment by fedebassetti** [comment]
The Jedi is really cool and matches the ancient symbols.
Another option is the fist or the lion 
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQILsWx2rNxpXJbhav91ks6kzB0IomuXjM668YdFAQsJ2DM58cM

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7kZ8wmelpJ6sKVqdMq39sJDMIsOYbpVzJ5_mnnYMx26-CAlws

**Comment by fedebassetti** [comment]
Attentive https://www.google.com/search?q=attentive%20symbol&ie=utf-8&oe=utf-8&client=firefox-b-1-m#imgrc=S9ScWs77TO9UmM:

**Comment by cwalters126** [comment]
i used font awesome

**Comment by fedebassetti** [comment]
@cwalters126 inspiredlab is on v2 of fontanwesome. So we might go live and pretty much plan for a refresh.
We'll revisit on another occasion as we develop our own themes.
Thank you for digging them out.
