### ISSUE TITLE
cache inspiredlab site

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#25]
do we have a cache plugin and if so do we keep it?
https://github.com/benbalter/jekyll-include-cache[https://github.com/benbalter/jekyll-include-cache](https://github.com/benbalter/jekyll-include-cache)

**Comment by Stevendh** [comment]
Doesn't look like it. Do you think it's something we may need?

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/65285570-7d4b1180-db02-11e9-9148-e46ed25868ed.png)
@Stevendh
