### ISSUE TITLE
move pictures on team page

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#32]
move the pictures before the name on the team page of inspired lab. 53x53, go see the style from the OMIS gazette (circles).

**Comment by fedebassetti** [comment]
@inspiredlab/interns please check the `Apply` button on the `join` page. 
let me know if you can apply.

**Comment by cwalters126** [comment]
On Oct 20, 2019, at 02:24, Federico Bassetti <notifications@github.com<mailto:notifications@github.com>> wrote:


@inspiredlab/interns<https://github.com/orgs/inspiredlab/teams/interns> please check the Apply button on the join page.
let me know if you can apply.

**Comment by cwalters126** [comment]
I cant. It moves around and then at some point it quits but nothing happens when i click

On Oct 20, 2019, at 02:24, Federico Bassetti <notifications@github.com<mailto:notifications@github.com>> wrote:


@inspiredlab/interns<https://github.com/orgs/inspiredlab/teams/interns> please check the Apply button on the join page.
let me know if you can apply.
