### ISSUE TITLE
Elusive Apply button

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#53]
Add simple gamification behavior to the apply button
- [x] move side by side 
- [x] randomize a funny response
- [x] use a double click to trigger the application process
- [x] add an effect on a single click

**Comment by fedebassetti** [comment]
[](https://federicobassetti.typeform.com/to/o47nwe)

**Comment by Stevendh** [comment]
I did it. I poured my heart and soul into my application.

**Comment by fedebassetti** [comment]
@Stevendh any other feedback? what was the user experience like? 
@cwalters126 
@chrisjzamora8

**Comment by Stevendh** [comment]
I thought the transitions were smooth, the questions themselves seemed relevant - although I'm sure we'll change/add things over time. Overall, I think the choice of that app service was a solid one.

**Comment by fedebassetti** [comment]
Any questions we should reword?
The more open style they are the better.

**Comment by Stevendh** [comment]
I would consider putting the core values on the page of the question that ask about them.

**Comment by fedebassetti** [comment]
I added the effect on the one click, so it shakes, see if you can catch it.
The tag lines are now in red.

**Comment by fedebassetti** [comment]
it has been tested around and it's good to go live.

**Comment by Stevendh** [comment]
How exactly does this work? Does it email you the results of the app or does it store the apps somewhere in this repos?

**Comment by fedebassetti** [comment]
It’s a secret

**Comment by Stevendh** [comment]
-_-

How do you take tacos away from someone?
