### ISSUE TITLE
6. Hypothesis

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#64]
Combine the assumptions from 2, 3, 4 & 5 into the following hypothesis statement:
“We believe that [business outcome] will be achieved if [user] attains [benefit] with [feature].”
(Hint: Each hypothesis should focus on one feature only.

**Comment by cwalters126** [comment]
“We believe that student will apply to inspired lab if student attains information about experiential learning opportunities with product descriptions.”
“We believe that student will apply to inspired lab if student attains information about inspired lab team with team membership page.”
“We believe that student will apply to inspired lab if student attains information experiential learning opportunities with inspired lab workshops.”
“We believe that student will apply to inspired lab if student contacts inspired lab about learning opportunities with the contact form.”

**Comment by fedebassetti** [comment]
@cwalters126 @arturwhite1 @RaviHarsha  @leenabusalem the canvas is updated with the solution ideas. Take a look and make suggestions as needed.

**Comment by RaviHarsha** [comment]
@fedebassetti: I agree with the statements posted and maybe we could also add one like
"We believe that student will apply to the inspired lab if student attains information about experimental learning opportunities with **success stories**"
