### ISSUE TITLE
8. the least amount of work we need to do to learn the next most important thing?

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#66]
What’s the least amount of work we need to do to learn the next most important thing?
Design experiments to learn as fast as you can whether your riskiest assumption is true or false

**Comment by cwalters126** [comment]
Have a cool project and position it so that students are compelled to join. 
- stories 
- <a href="https://studio.knightlab.com/projects/auditing-news-on-smart-speakers/">example</a>

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/84801162-733c3d80-afc4-11ea-8db3-4e42266934a1.png)

The Mural is now updated with this info.
