### ISSUE TITLE
Setup repo for Mundana adoption

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#70]
We now have a repo called **MaterialGirl**  it available in inspired lab for the development of the new inspired lab Jekyll theme.

**Comment by fedebassetti** [comment]
@z1879079 the repo from Mundana is at the official site: https://jekyllthemes.io/theme/mundana
![image](https://user-images.githubusercontent.com/1824246/84696810-ad4d0700-af12-11ea-8422-1fbee3135a2e.png)

github repo: https://github.com/wowthemesnet/mundana-theme-jekyll

**Comment by fedebassetti** [comment]
- [ ] clone materialgirl 
- [ ] make a new branch
- [ ] download Mundana theme from GitHub 
- [ ] unzip the files
- [ ] copy the files in the new materialgirl branch
- [ ] build it locally with jekyll

**Comment by fedebassetti** [comment]
@z1879079 I'll setup up the pages for you.

**Comment by leenabusalem** [comment]
getting an authorization error when cloning materialgirl

**Comment by fedebassetti** [comment]
@leenabusalem screenshot. Where are you experiencing the issue?
