### ISSUE TITLE
Mundana reusable components

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#72]
identify the reusable component of the Mundana theme.

What is there in the Mundana theme that we can freely use in our theme without attribution.

Acceptance Criteria: working theme as stripped-down Mundana theme

**Comment by arturwhite1** [comment]
Lunr, Bootstrap are all reusable components. Some of the JS is also reusable.

**Comment by fedebassetti** [comment]
@cwalters126 @leenabusalem @cwalters126 this issue could be a good Wednesday activity.
We mob program our Jekyll theme
