### ISSUE TITLE
photo & and bio for "authors" 

### ISSUE THREAD

**Issue by leenabusalem** [inspiredlab/inspiredlab.github.io#74]
Please write a short bio of yourself that we can include in our "team" tab of the InspiredLab website. Look at the original website for reference (of length, content, etc.)

NOTE: Please include a link to a photo of yourself, whether that is from your Github  profile or LinkedIn.

**Comment by cwalters126** [comment]
Bio: "My name is Casey and I am a recent graduate of the NIU Management Information Systems program. As a member of the InspirEd Lab team, I have had the opportunity to develop a graph database using Neo4j, act as the product owner of the OM&IS Gazette, and help out on other projects I found interesting. In the future, I hope to become a Product Owner at a company that uses an Agile methodology to work on IT projects and products. Being a part of Inspired Lab has challenged me to think in an agile mindset and embrace change."
Stay tuned for picture, I haven't decided yet

**Comment by leenabusalem** [comment]
"I am a senior studying Operations Management and Information Systems with a Business Analytics Minor at Northern Illinois University. As an InspirEd Lab team member, I have built in-depth knowledge of tools like GitHub, Jekyll, Toggl, Mural, etc. I have also had numerous opportunities to expand my knowledge by working alongside mentors on the OM&IS Gazette. My goal is to become a well rounded asset for a company that would perpetuate my growth in all aspects of Business. Being a part of the InspirEd Lab team has aided me in reaching this goal."

Not sure if this works, but if not.. stay tuned
https://media-exp1.licdn.com/dms/image/C5603AQGyyjhYAj_TKg/profile-displayphoto-shrink_400_400/0?e=1597881600&v=beta&t=xvTJc6E5EEgACVz0DdeGW-7HnAG8rmPgVZCjdd-W5qo

**Comment by cwalters126** [comment]
it worked perfect @leenabusalem !

picture included here: https://user-images.githubusercontent.com/47012763/84933185-20818500-b09b-11ea-9b7a-a9350e0ef80d.JPG

**Comment by fedebassetti** [comment]
When using a linkedin picture 
![image](https://user-images.githubusercontent.com/1824246/84938005-3cd4f000-b0a2-11ea-826d-e61562a0f9c2.png)
