### ISSUE TITLE
reuse linked in profile picture in team page

### ISSUE THREAD

**Issue by fedebassetti** [inspiredlab/inspiredlab.github.io#75]
Please explore the possibility of linking in a profile picture from either github or Linkedin for the author page in the mundane theme. Check #74 for links

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/84937916-1a42d700-b0a2-11ea-9efc-847dd296d673.png)

**Comment by RaviHarsha** [comment]
I have done some testing and it looks good with the approach which we have discussed the other day. I have attached the step by step document which could help us to replicate the same in our final theme design.
[Profile picture link.docx](https://github.com/inspiredlab/inspiredlab.github.io/files/4801463/Profile.picture.link.docx)

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/85078273-ada30780-b189-11ea-913c-cdc1319712c4.jpeg)

**Comment by fedebassetti** [comment]
@RaviHarsha thank you!

Ps: use markdown as much as possible (no cool data scientist uses it :happy:)
