### ISSUE TITLE
Ravi - Bio and Picture

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#86]
Please write a short bio of yourself that we can include in our "team" tab of the InspiredLab website. Look at the original website for reference (of length, content, etc.)

NOTE: Please include a link to a photo of yourself, whether that is from your Github profile or LinkedIn.

**Comment by RaviHarsha** [comment]
Bio information: https://www.linkedin.com/in/ravi-harsha-b7405079/edit/about/
Profile picture: https://github.com/RaviHarsha.png

**Comment by fedebassetti** [comment]
@RaviHarsha The bio link doesn’t resolve. I think it’s private. Can you try from your public profile link?

**Comment by RaviHarsha** [comment]
**Bio:** www.linkedin.com/in/ravi-harsha-b7405079
                                           (or)
My name is Ravi harsha and I am a graduate student at Northern Illinois university in Management Information Systems program. I am an enthusiastic person with knowledge in SAP HANA, SAP FICO, SQL, Power BI, Power pivot, Power excel with basic knowledge in HTML and CSS. I have also utilized tools such as Github, Flipgrid and Toggle. I am looking forward to adapt, enhance and learn new skills and utilize in all the possible domains.
