### ISSUE TITLE
Project Stories - OMIS Gazette

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#87]
Track down the Alexa skill post on the OMIS Gazette and tweak to fit onto the inspired lab website

**Comment by leenabusalem** [comment]
@fedebassetti should this be done right on explorer? Don't have access to writing rights in visual studio... not sure how to directly add images for this story without it

**Comment by fedebassetti** [comment]
@leenabusalem let me check permissions

**Comment by leenabusalem** [comment]
@fedebassetti thank you... i submitted a draft of some sort for merge?? let me know what to fix!
