### ISSUE TITLE
Featured Story - New Member Ravi

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#90]
Create a featured story in Markdown (1 page) about finding Inspired Lab and joining the team. tell us a little about what you are interested in, what projects you will be on, first impressions, etc.

**Comment by RaviHarsha** [comment]
Please find the story attached. 
[My story.docx](https://github.com/inspiredlab/inspiredlab.github.io/files/4841344/My.story.docx)

**Comment by fedebassetti** [comment]
@RaviHarsha Thank your for working on it.
Please make it as Markdown file so @leenabusalem can take a look at it

**Comment by RaviHarsha** [comment]
Please find the markdown file below:
**Git hub Markdown**: https://github.com/RaviHarsha/Test
**Webpage**: https://raviharsha.github.io/Test/
**Notepad file**:( save it in .md format and u could get the mark down file on your desktop)
[Inspired lab story.txt](https://github.com/inspiredlab/inspiredlab.github.io/files/4841641/Inspired.lab.story.txt)

**Comment by leenabusalem** [comment]
@RaviHarsha thank you!! I’ll take a look ASAP

**Comment by leenabusalem** [comment]
@fedebassetti taking my time with this so I can use it in Wednesday’s demo thing
