### ISSUE TITLE
Project Stories - MLH Workshops

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#91]
Find post about MLH events on OMI Sgazette (if they dont exist, youll have to create the post from scratch) and tweak to fit the inspired lab website. 

Search for DSP press release for some  ✨ i n s p i r a t i o n ✨

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/85333267-eb13d780-b49e-11ea-8f10-f9f4564aaf06.png)

**Comment by fedebassetti** [comment]
@leenabusalem @cwalters126 that's what i found

**Comment by fedebassetti** [comment]
@leenabusalem I think this one is also good one that can be done fast.

**Comment by fedebassetti** [comment]
we might have this picture on inspiredlab twitter feed and could be a place to store some of our images 😄
